version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: zorvyn-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: zorvyn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '55432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d zorvyn']
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zorvyn-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/zorvyn?schema=public
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
